### ISSUE TITLE
Travis build not enabled

### ISSUE THREAD

**Issue by palfrey** [socketcan-rs/socketcan-rs#25]
There's a .travis.yml in the source code, but https://travis-ci.org/socketcan/socketcan-rs isn't enabled

**Comment by fpagliughi** [comment]
Are people still using Travis in general? I've been trying to move my projects to GitHub Actions.

**Comment by fpagliughi** [comment]
Actually... see #21

**Comment by fpagliughi** [comment]
#21 replaced Travis with GitHub Actions
