### ISSUE TITLE
CAN-FD Support

### ISSUE THREAD

**Issue by jreppnow** [socketcan-rs/socketcan-rs#27]
Hello everyone!

Thank you very much for this useful crate! 

Are there any plans to support **CAN-FD** in addition to standard CAN 2.0 within the scope of this crate? 

If yes, I would certainly be willing to get started on the topic and contribute, as I need it for another project I am working on atm. 

One problem I am seeing is the API - ideally, one would avoid duplicating all the structs for CAN-FD, as to have a unified interface. But especially ```CANFrame``` would blow up quite drastically in size, as CAN-FD payloads are up to 64 bytes. This would make copying the struct a lot more expensive as well. One option would be to keep the payload in a Vec or some other heap-allocated container in the CAN-FD case, but that adds an arguable unnecessary allocation. Happy to hear your thoughts on the matter! 

Best regards, 
Janosch.

**Comment by fpagliughi** [comment]
There is an existing PR that I am going to start looking at soon to merge: #16.
Please feel free to comment on it.
