### ISSUE TITLE
Are the examples out of date for v1.7.0?

### ISSUE THREAD

**Issue by therishidesai** [socketcan-rs/socketcan-rs#36]
It seems like all the examples don't build for v1.7.0

**Comment by fpagliughi** [comment]
Do you mean the examples currently in `master`?

If so, then no, they will not work with v1.7.0. The master branch is preparing for a major update to v2.0. So, relative to that, it's v1.7.0 that is out of date.

**Comment by therishidesai** [comment]
```
12 | use socketcan::{CanFrame, CanSocket, Frame, Socket};
   |                 ^^^^^^^^  ^^^^^^^^^  ^^^^^  ^^^^^^ no `Socket` in the root
   |                 |         |          |
   |                 |         |          no `Frame` in the root
   |                 |         no `CanSocket` in the root
   |                 no `CanFrame` in the root
   |
   = help: consider importing this trait instead:
           embedded_can::Frame
help: a similar name exists in the module
   |
12 | use socketcan::{CANFrame, CanSocket, Frame, Socket};
   |                 ~~~~~~~~
help: a similar name exists in the module
   |
12 | use socketcan::{CanFrame, CANSocket, Frame, Socket};
   |                           ~~~~~~~~~
help: a similar name exists in the module
   |
12 | use socketcan::{CanFrame, CanSocket, Frame, socket};
```

The blocking example fails to build with the following. I can rename `CanFrame` and `CanSocket` easily but I'm not sure where `Frame` comes from.

**Comment by therishidesai** [comment]
Also it looks like the `CANSocket` type doesn't have a `receive` funciton.

**Comment by fpagliughi** [comment]
The examples work with v2.0
The examples **do not** work with v1.7.0

v2.0 is not released yet.

There are a significant number of breaking changes in v2.0

**Comment by therishidesai** [comment]
Ah ok, I misread your initial reply.

**Comment by fpagliughi** [comment]
No worries. I need to get back to this and get v2.0 released. I agree. It's confusing.

**Comment by therishidesai** [comment]
Do you have an estimated time as to when 2.0 will be out?
