### ISSUE TITLE
Example provided does not build 

### ISSUE THREAD

**Issue by Kampouse** [socketcan-rs/socketcan-rs#47]
the example  provided in the readme either as typo as wrong  import but in the current state is not  building

**Comment by fpagliughi** [comment]
The one in _master?_ That got copy/pasted when the socketcan-tokio crate was merged, and I probably didn't even try to test it. I may test and fix it, but more likely I will remove it. It tends to be problematic keeping samples in the README file(s) as they tend to diverge from the actual code base. Better to just defer to the example apps, or put code in the source doc and let the tests ensure that they compile.
