### ISSUE TITLE
Version 3.3.0 Not Compiling With Neli

### ISSUE THREAD

**Issue by Peyton-McKee** [socketcan-rs/socketcan-rs#56]
Hi SocketCan Team, Im working on an embedded project and am trying to build socket can for the newer versions, however any version above 2.0.0 fails to compile when I cargo build due to what seems to be a conflict with the neli library. 

My Cargo.toml looks like this 
```[package]
name = "calypso"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
socketcan = "3.3.0"
paho-mqtt = "0.12.3"
nalgebra = "0.32.3"
```

When I move socketcan down to version 1.7.0 it compiles and works fine, but I want to upgrade to 3.3.0. All 2.x versions fail.

Heres some sample Terminal output from my cargo build command. 
<img width="595" alt="Screenshot 2023-12-01 at 12 37 25 AM" src="https://github.com/socketcan-rs/socketcan-rs/assets/113635669/80f947fd-773b-4ffe-b863-8b07dd5b544a">

Any advice would be much appreciated

**Comment by fpagliughi** [comment]
Much of the work for versions 3.1 and 3.2 were to add additional Netlink support to the crate using neli, so things were working well a few weeks ago.

What platform are you targeting?

**Comment by Peyton-McKee** [comment]
I’m currently developing on mac, targeting a raspberry pi however its not compiling on my machine, I havn’t tested it on the pi.

**Comment by fpagliughi** [comment]
Ummm... does a Mac even have SocketCAN? Or Netlink? I thought those were pretty Linux-specific subsystems. I have no plans of trying to support this on any other OS than Linux.

**Comment by Peyton-McKee** [comment]
Hmm, yeah I’m not trying to run the program on the mac, just trying to build it. The actual program runs solely on raspberry pis. Maybe I should just work in a dev environment on docker.

**Comment by fpagliughi** [comment]
Yeah, unless you're specifically targeting a Linux system, you won't have the correct components from the upstream libraries.

Have you tried `cross`? I haven't used it on this project specifically, but I do use it a lot when developing the Paho Rust stuff. It's pretty nice.

**Comment by Peyton-McKee** [comment]
I have not, havn’t heard of it actually. Ill look into that. This is the first rust program I’ve created so still learning all the rusty features.

**Comment by fpagliughi** [comment]
Yeah, cross is a container system for cross-compiling rust. Basically wraps and acts like cargo.
https://github.com/cross-rs/cross

If you already have docker installed, it can use that. Otherwise it can use Podman, I think.

**Comment by baxterjo** [comment]
> Perhaps I should put in a _build.rs_ file which fails with a clear, distinct message on non-Linux targets.

That could be helpful, maybe add a note that refers to cross compilation for development or even just refers to this ticket.
