### ISSUE TITLE
Tokio-Async CanFd not capable of sending RemoteFrame?

### ISSUE THREAD

**Issue by AsimmHirani** [socketcan-rs/socketcan-rs#57]
I noticed that the Sync and async-io implementations of write_frame followed the CanAnyFrame usage pattern for the CanFdSocket, however the implementation in tokio.rs was only capable of sending CanFdFrames. Is there a reason for this API difference for Tokio vs async-io and sync?

Sync write_frame:
https://github.com/socketcan-rs/socketcan-rs/blob/master/src/socket.rs#L648

async-io write_frame:
https://github.com/socketcan-rs/socketcan-rs/blob/master/src/async_io.rs#L90

tokio write_frame:
https://github.com/socketcan-rs/socketcan-rs/blob/master/src/tokio.rs#L163

This is impacting a project where we are trying to send RemoteFrames over a CanFdSocket asynchronously using tokio. Do you have any information about this usecase?

**Comment by EliteTK** [comment]
I also ran into this. Sounds like fixing this would require a breaking change.

**Comment by fpagliughi** [comment]
Sorry for the slow response. This library is really a group effort by a lot of contributors. I took over maintaining it a while back but only use a small subset of it on occasion. So inconsistencies pop up and I rely on all you folks to let me know. I'll test out the PR and get it in with the next release if it looks good.
