### ISSUE TITLE
No way to mutate CanFrame

### ISSUE THREAD

**Issue by kjetilkjeka** [socketcan-rs/socketcan-rs#9]
I'm currently writing a [rust lib](https://github.com/UAVCAN/uavcan.rs) for [uavcan](uavcan.org). I'm planning to use socketcan as the main testing platform (for convenience reasons).

The way the ```CanFrame``` is currently structured there's no way to mutate the dlc/data after a frame has been created. That means I will have to work with an intermediate structure until the moment I'm ready to transfer, then convert it into a ```socketcan::CanFrame```.

Would you mind exposing some methods which makes it possible to implement something similar to the following trait?

    pub trait TransferFrame {
    /// Maximum data length the transfer protocol supports.
    const MAX_DATA_LENGTH: usize;

    /// Create a new TransferFrame with id: id, and length 0.
    /// Data length can be changed with `set_data_length(&self)`.
    /// Data can be changed with `data_as_mut(&mut self)`.
    fn new(id: TransferFrameID) -> Self;

    /// Returns the 28 bit ID of this TransferFrame.
    ///
    /// When deciding which frame that will be transmitted,
    /// the ID is used to prioritze (lower ID means higher priority)
    fn id(&self) -> TransferFrameID;

    /// Returns a slice with the data in this TransferFrame
    ///
    /// Length can be found by checking the length
    /// of this slice `self.data().len()`
    fn data(&self) -> &[u8];

    /// Returns a mutable slice with the data in this TransferFrame
    /// use this method to set/change the data inside this TransferFrame
    fn data_as_mut(&mut self) -> &mut[u8];

    /// Set the data length of this TransferFrame
    ///
    /// ## Panics
    /// `set_data_lengt(&mut self, length: usize)` should panic if `length > T::MAX_DATA_LENGTH`
    fn set_data_length(&mut self, length: usize);

**Comment by fpagliughi** [comment]
Oops. I forgot about this one. But it will be the last thing I get in for v2.0.

I think it would be dangerous to change the data and data lengths separately. Better to just allow the app to set a new data slice, and take the length of that automatically, like:
```
fn set_data(&mut self, data: &[u8]) -> Result<()>;
```
Something like that. 

I suppose you could also change the ID. Like a `set_id(...) ` function.
